import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [
  //   {
  //     type: 'autogenerated', dirName: '.'}
  // ],

  // But you can create a sidebar manually
  
  docSidebar: [
    {
      type: 'html',
      value: '<div style="margin-top: 20px; margin-bottom: 8px; font-size: 12px; font-weight: 700; display: flex; align-items: center; gap: 8px; color: var(--ifm-color-primary); text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.9;"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="16" width="16" xmlns="http://www.w3.org/2000/svg"><path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z"></path><path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z"></path><path d="M9 12H4s.55-3.03 2-5c1.62-2.2 5-3 5-3"></path><path d="M12 15v5s3.03-.55 5-2c2.2-1.62 3-5 3-5"></path></svg> GET STARTED</div>',
      defaultStyle: true,
    },
    'GetStarted/Overview',
    'GetStarted/Quickstart',
    'GetStarted/Models',
    
    {
      type: 'html',
      value: '<div style="margin-top: 20px; margin-bottom: 8px; font-size: 12px; font-weight: 700; display: flex; align-items: center; gap: 8px; color: var(--ifm-color-primary); text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.9;"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="16" width="16" xmlns="http://www.w3.org/2000/svg"><rect x="9" y="3" width="6" height="6" rx="1"></rect><rect x="3" y="15" width="6" height="6" rx="1"></rect><rect x="15" y="15" width="6" height="6" rx="1"></rect><path d="M12 9v6"></path><path d="M12 15H6v0"></path><path d="M12 15h6v0"></path></svg> AI FRAMEWORK</div>',
      defaultStyle: true,
    },
    'AgenticNetwork/introduction',
    'AgenticNetwork/Create_simple_agent',
    'AgenticNetwork/Create_agentic_network',
    'AgenticNetwork/Agent_configuration',
    {
      type: 'category',
      label: 'Configuration',
      collapsed: false,
      items: [
        'AgenticNetwork/Configuration/Initialization',
        'AgenticNetwork/Configuration/LLM',
        'AgenticNetwork/Configuration/Tools',
        'AgenticNetwork/Configuration/Agent_function',
        'AgenticNetwork/Configuration/Edges',
      ],
    },
    {
      type: 'html',
      value: '<div style="margin-top: 20px; margin-bottom: 8px; font-size: 12px; font-weight: 700; display: flex; align-items: center; gap: 8px; color: var(--ifm-color-primary); text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.9;"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="16" width="16" xmlns="http://www.w3.org/2000/svg"><rect x="3" y="11" width="18" height="10" rx="2"></rect><circle cx="12" cy="5" r="2"></circle><path d="M12 7v4"></path><line x1="8" y1="16" x2="8" y2="16"></line><line x1="16" y1="16" x2="16" y2="16"></line></svg> AGENTS</div>',
      defaultStyle: true,
    },
    'Agents/validate_config',
    'Agents/test_agent',
    'Agents/create_agent',
    'Agents/run_agent',
    // 'Agents/chat_history',
    'Agents/get_agent_details',
    'Agents/list_agents',
    'Agents/update_agent_info',
    'Agents/delete_agent',

    {
      type: 'html',
      value: '<div style="margin-top: 20px; margin-bottom: 8px; font-size: 12px; font-weight: 700; display: flex; align-items: center; gap: 8px; color: var(--ifm-color-primary); text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.9;"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="16" width="16" xmlns="http://www.w3.org/2000/svg"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10"></path></svg> KEYVAULT</div>',
      defaultStyle: true,
    },
    'Keyvault/Keyvault',
    // {
    //   type: 'category',
    //   label: 'How to use',
    //   collapsed: true,
    //   items: [
    //     'Keyvault/how to use/Add keys',
    //     'Keyvault/how to use/Usage',
    //     'Keyvault/how to use/Revoke keys',
    //   ],
    // },

    {
      type: 'html',
      value: '<div style="margin-top: 20px; margin-bottom: 8px; font-size: 12px; font-weight: 700; display: flex; align-items: center; gap: 8px; color: var(--ifm-color-primary); text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.9;"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="16" width="16" xmlns="http://www.w3.org/2000/svg"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"></path></svg> TOOLS</div>',
      defaultStyle: true,
    },
    'Tools/Understanding_Tools',
    'Tools/list_of_tools',
    {
      type: 'category',
      label: 'Tools',
      collapsed: false,
      items: [
        'Tools/ToolList/API',
        'Tools/ToolList/Arxiv',
        'Tools/ToolList/AWS_Lambda',
        'Tools/ToolList/AWS_SES_send_email',
        'Tools/ToolList/DatabaseTool',
        'Tools/ToolList/DatabaseToolReadOnly',
        'Tools/ToolList/GitHubTool',
        'Tools/ToolList/JiraTool',
        'Tools/ToolList/Outlook',
        'Tools/ToolList/Pinecone',
        'Tools/ToolList/Tavily',
        'Tools/ToolList/Twilio_sms',
        'Tools/ToolList/Twilio_whatsapp',
        'Tools/ToolList/webpage_search',
        'Tools/ToolList/Wikipedia',
        'Tools/ToolList/Zapier',
      ],
    },
    {
      type: 'html',
      value: '<div style="margin-top: 20px; margin-bottom: 8px; font-size: 12px; font-weight: 700; display: flex; align-items: center; gap: 8px; color: var(--ifm-color-primary); text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.9;"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="16" width="16" xmlns="http://www.w3.org/2000/svg"><ellipse cx="12" cy="5" rx="9" ry="3"></ellipse><path d="M3 5V19A9 3 0 0 0 21 19V5"></path><path d="M3 12A9 3 0 0 0 21 12"></path></svg> KNOWLEDGE REPO</div>',
      defaultStyle: true,
    },
    'Knowledge Repository/Overview',
    {
      type: 'category',
      label: 'Connectors',
      collapsed: false,
      items: [
        'Knowledge Repository/Connectors/URL',
        'Knowledge Repository/Connectors/AWS S3',
        'Knowledge Repository/Connectors/Confluence',
        'Knowledge Repository/Connectors/Sharepoint',
      ],
    },
    {
      type: 'html',
      value: '<div style="margin-top: 20px; margin-bottom: 8px; font-size: 12px; font-weight: 700; display: flex; align-items: center; gap: 8px; color: var(--ifm-color-primary); text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.9;"><svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round" height="16" width="16" xmlns="http://www.w3.org/2000/svg"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="16" x2="12" y2="12"></line><line x1="12" y1="8" x2="12.01" y2="8"></line></svg> RESOURCES</div>',
      defaultStyle: true,
    },
    'additional/YAML_Conversion_Guide',

   
  ],
};

export default sidebars;
