const fs = require('fs');
const path = require('path');

const DOCS_DIR = path.join(__dirname, '../docs');
const STATIC_DIR = path.join(__dirname, '../static');
const SIDEBAR_PATH = path.join(__dirname, '../sidebars.ts');
const OUTPUT_PATH = path.join(STATIC_DIR, 'llms.txt');

// Helper to extract frontmatter title and description
function getFrontmatter(filePath) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const match = content.match(/^---([\s\S]*?)---/);
    if (!match) return { title: '', description: '' };
    
    const yaml = match[1];
    const titleMatch = yaml.match(/(?:title|sidebar_label)\s*:\s*(?:"([^"]+)"|'([^']+)'|([^\n]+))/);
    const descMatch = yaml.match(/description\s*:\s*(?:"([^"]+)"|'([^']+)'|([^\n]+))/);
    
    let title = titleMatch ? (titleMatch[1] || titleMatch[2] || titleMatch[3]).trim() : '';
    let description = descMatch ? (descMatch[1] || descMatch[2] || descMatch[3]).trim() : '';
    
    // Clean up quotes if any remain
    title = title.replace(/^['"]|['"]$/g, '');
    description = description.replace(/^['"]|['"]$/g, '');
    
    return { title, description };
  } catch (err) {
    return { title: '', description: '' };
  }
}

// Find files in autogenerated directories recursively
function getDocsInDir(dirName) {
  const dirPath = path.join(DOCS_DIR, dirName);
  if (!fs.existsSync(dirPath)) return [];
  
  const files = [];
  function recurse(currentPath) {
    const list = fs.readdirSync(currentPath);
    list.forEach(file => {
      const fullPath = path.join(currentPath, file);
      const stat = fs.statSync(fullPath);
      if (stat.isDirectory()) {
        recurse(fullPath);
      } else if (file.endsWith('.md') || file.endsWith('.mdx')) {
        const relPath = path.relative(DOCS_DIR, fullPath);
        // Remove extension
        const docId = relPath.replace(/\.mdx?$/, '');
        files.push(docId);
      }
    });
  }
  recurse(dirPath);
  return files;
}

// Parse sidebars.ts and generate plain-text catalog
function generate() {
  console.log('Generating llms.txt...');
  
  if (!fs.existsSync(SIDEBAR_PATH)) {
    console.error('sidebars.ts not found');
    return;
  }
  
  const sidebarContent = fs.readFileSync(SIDEBAR_PATH, 'utf-8');
  const lines = sidebarContent.split('\n');
  
  let markdown = `# SVAHNAR AI Developer Documentation\n\n`;
  markdown += `This file serves as a plain-text index of the SVAHNAR documentation, optimized for LLMs, AI agents, and developers.\n\n`;
  
  let currentCategory = '';
  const processedDocs = new Set();
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    
    // Skip comments and empty lines
    if (line.startsWith('//') || line === '') continue;
    
    // Check for category label
    const categoryMatch = line.match(/label\s*:\s*['"]([^'"]+)['"]/);
    if (categoryMatch) {
      currentCategory = categoryMatch[1];
      markdown += `\n## ${currentCategory}\n\n`;
      continue;
    }
    
    // Check for autogenerated directory (like connectors/tool lists)
    const autoMatch = line.match(/dirName\s*:\s*['"]([^'"]+)['"]/);
    if (autoMatch) {
      const dirName = autoMatch[1];
      const files = getDocsInDir(dirName);
      files.forEach(docId => {
        if (processedDocs.has(docId)) return;
        processedDocs.add(docId);
        
        let filePath = path.join(DOCS_DIR, `${docId}.md`);
        if (!fs.existsSync(filePath)) {
          filePath = path.join(DOCS_DIR, `${docId}.mdx`);
        }
        
        const fm = getFrontmatter(filePath);
        const title = fm.title || path.basename(docId);
        const desc = fm.description ? `: ${fm.description}` : '';
        markdown += `- [${title}](/docs/${docId})${desc}\n`;
      });
      continue;
    }
    
    // Check for direct doc path ID
    const docMatch = line.match(/^['"]([^'"]+)['"]\s*,?$/);
    if (docMatch) {
      const docId = docMatch[1];
      if (processedDocs.has(docId)) continue;
      processedDocs.add(docId);
      
      let filePath = path.join(DOCS_DIR, `${docId}.md`);
      if (!fs.existsSync(filePath)) {
        filePath = path.join(DOCS_DIR, `${docId}.mdx`);
      }
      
      if (fs.existsSync(filePath)) {
        const fm = getFrontmatter(filePath);
        const title = fm.title || path.basename(docId);
        const desc = fm.description ? `: ${fm.description}` : '';
        markdown += `- [${title}](/docs/${docId})${desc}\n`;
      }
    }
  }
  
  fs.writeFileSync(OUTPUT_PATH, markdown);
  console.log('Successfully generated llms.txt at static/llms.txt!');
}

generate();
